# Generated by Django 3.2.18 on 2023-12-05 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0003_auto_20231205_0031'),
        ('posts', '0003_auto_20230529_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mountain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mountains.mountain'),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
