# Generated by Django 3.2.18 on 2023-12-05 00:31

from django.db import migrations, models
import imagekit.models.fields
import mountains.models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0002_auto_20230607_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'managed': False, 'ordering': ['crs_name_detail']},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=mountains.models.Review.image_path),
        ),
    ]
